version: '3.7'

services:
  cloudflare-clear-ip-rules:
    build: .
    image: nfg/cloudflare-clear-ip-rules:latest
    volumes:
      - .:/build
      # - /build/node_modules
    command: npm run docker-compose
    environment:
      - TERM=xterm-256color
      - NODE_OPTIONS=--enable-source-maps
    stdin_open: true
    tty: true
    ports:
      - '3000:1234'
      - '9229:9229'
